### ISSUE TITLE
applying filters in icerate causes crash

### ISSUE THREAD

**Issue by njwilson23** [njwilson23/irlib#9]
Applying a filter (e.g. `f gc`) in icerate causes a crash with a message about `filter_defs`. Probably moved that around last time the filter system was refactored.

**Comment by njwilson23** [comment]
Traceback:

    Traceback (most recent call last):
      File "/home/natw/venv-default2.7/bin/icerate.py", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/home/natw/code/irlib/icerate.py", line 454, in <module>
        main()
      File "/home/natw/code/irlib/icerate.py", line 451, in main
        R, L = HandleCommand(s, infile, R, L, S)
      File "/home/natw/code/irlib/icerate.py", line 352, in HandleCommand
        irlib.filter_defs.ApplyFilter(L, args[1:])
    AttributeError: 'module' object has no attribute 'filter_defs'
